blog/models.py
from blog import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    # image = db.Column()

    # initialise
    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    # check password
    def __check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"UserName: {self.username}"

blog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import  DataRequired, Email, EqualTo
from wtforms import ValidationError
from blog.models import User

# create LoginForm
class LoginForm(FlaskForm):
        email = StringField('Email', validators = [DataRequired()])
        username = StringField('Username', validators = [DataRequired()])
        password = PasswordField('Password', validators = [DataRequired()])
        submit = SubmitField('Login')
        # image =


# create RegistrationForm
class RegistrationForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    username = StringField('Username', validators = [DataRequired()])
    password = PasswordField('Password', validators = [DataRequired(), EqualTo('password_confirm', message = 'Passwords must match')])
    password_confirm = PasswordField('Confirm Password', validators = [DataRequired()])
    submit = SubmitField('Register')

    # check that emails haven't already been used
    def validate_email(self, field):
        # Check if not None for that user email!
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def validate_username(self, field):
        # Check if not None for that username!
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Sorry, that username is taken!')

blog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_debugtoolbar import DebugToolbarExtension

app = Flask(__name__)

# the toolbar is only enabled in debug mode:
app.debug = True


###############
### CONFIGS ###
###############
app.config['SECRET_KEY'] = 'mykey'

# set up Debug sidebar
toolbar = DebugToolbarExtension(app)

################################
##### SQL DATABASE SECTION #####
import os
basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)


# pass the app to the loginManager
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login' # this will be one of the views (routes)

# register blueprints
from blog.users.views import users_blueprint
app.register_blueprint(users_blueprint, url_prefix='/users')

from blog.core.views import core_blueprint
app.register_blueprint(core_blueprint, url_prefix='/core')

blog/core/__init__.py
# This file is empty. It's here just because we need an __init__ file so we can import the module (in this case, the core module) to other parts of the project.

blog/core/views.py
from flask import Blueprint, Flask, redirect, render_template, url_for
from blog import db
from blog.models import User
# from blog.users.forms import LoginForm, RegistrationForm

core_blueprint = Blueprint('core', __name__)

@core_blueprint.route('/')
def index():
    return render_template('index.html')

blog/users/__init__.py
# This file is empty. It's here just because we need an __init__ file so we can import the module (in this case, the users module) to other parts of the project.

blog/users/views.py
from blog import app, db
from blog.models import User
from blog.users.forms import LoginForm, RegistrationForm
from flask import Blueprint, Flask, render_template, redirect, request, url_for, flash
from flask_login import login_user, login_required, logout_user, current_user

users_blueprint = Blueprint('users', __name__)

@users_blueprint.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, username=form.username.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering')
        return redirect(url_for('core.index'))
    return render_template('register.html', form=form)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Logged in successfully.')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html', form=form)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{{ title }}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../static/css/styles.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/png" href="../static/favicon.ico" />
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>

<body>
    <div class="header">
        <nav class="navbar fixed-top navbar-expand-sm">
            <button class="navbar-toggler hidden-sm" data-toggle="collapse" data-target="#navbarMenu">
                        <span class="navbar-toggler-icon">&#9776;</span>
                    </button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav">

                    <li><a href="{{url_for('core.index')}}">Home</a></li>

                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>

                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>

                </ul>
            </div>
        </nav>
    </div>

    <hr> {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>

</html>

blog/templates/index.html
{% extends "base.html" %} {% block content %}

<div class="container">

  <div class="row">
    <h1>Home page</h1>
  </div>

</div>

{% endblock %}

blog/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="container-fluid">
  <div class="row">
    <h1>Login</h1>
  </div>

  <form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group row">
      {{ form.username.label(class="col-sm-2 col-form-label") }} {{ form.username(class="col-sm-8") }}
    </div>

    <div class="form-group row">
      {{ form.password.label(class="col-sm-2 col-form-label") }} {{ form.password(class="col-sm-8")}}
    </div>

    <div class="form-group row">
      {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>



</div>
{% endblock %}

blog/templates/register.html
{% extends "base.html" %} {% block content %}

<div class="container">

  <div class="row">
    <h1>Register</h1>
  </div>

  <div class="row">
    <form method="POST">

      <div class="form-group row">
        {{ form.hidden_tag() }}
      </div>

      <div class="form-group row">
        {{ form.username.label(class="col-sm-2 col-form-label") }} {{ form.username(class="col-sm-8") }}
      </div>

      <div class="form-group row">
        {{ form.email.label(class="col-sm-2 col-form-label") }} {{ form.email(class="col-sm-8") }}
      </div>

      <div class="form-group row">
        {{ form.password.label(class="col-sm-2 col-form-label") }} {{ form.password(class="col-sm-8") }}
      </div>

      <div class="form-group row">
        {{ form.password_confirm.label(class="col-sm-2 col-form-label") }} {{ form.password_confirm(class="col-sm-8") }}
      </div>

      <div class="form-group row">
        {{ form.submit(class="btn btn-primary") }}
      </div>

      </form>
    </div>


  </div>

  {% endblock %}